name: ZAP Web Scan


  workflow_dispatch:   # 手動執行
  push:
    branches: [ "main" ]
on: permissions:
  contents: read
  issues: write
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://www.lulumatch.com/'
          fail_action: false
          artifact_name: 'zap-report'
